#! /bin/sh

mdtrj=$1
vzout=$2
frame=$3

APPDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cat <<END >c-ray-trailer
# walls
s	0 -1000 2		99		0.2 0.2 0.2			0.0	0.0

# lights
l	-50 100 -50

# camera
#	position	FOV		target
c	0 6 -17		45		0 -1 0
END

(
  awk "\$1 == $frame {for (i=2; i<NF; i++) printf \$i \" \"; print \$NF}" <$mdtrj | sed -e 's/^[0-9]\+ //' 

  cat c-ray-trailer
) | $APPDIR/c-ray >t.ppm

convert t.ppm $vzout 



